# Generated by Django 3.1.4 on 2020-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0002_sign_messages_useroverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_messages',
            name='door',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sign_messages',
            name='tuNumExt',
            field=models.TextField(default=''),
        ),
    ]
