# Generated by Django 3.1.4 on 2020-12-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0003_auto_20201228_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_Messages',
            new_name='mdlSignMessages',
        ),
    ]
