# Generated by Django 3.1.4 on 2020-12-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0004_auto_20201229_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlsignmessages',
            name='msgNum',
            field=models.IntegerField(default=-1),
        ),
    ]
