# Generated by Django 3.1.4 on 2021-01-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0005_mdlsignmessages_msgnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdlsignmessages',
            name='door',
            field=models.TextField(blank=True, default=''),
        ),
    ]
