# Generated by Django 3.1.4 on 2021-01-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0006_auto_20210118_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdlSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowsPerPage', models.IntegerField(default=5)),
                ('scrollSpeed', models.IntegerField(default=3)),
                ('pageDwell', models.IntegerField(default=10)),
            ],
        ),
    ]
