# Generated by Django 3.1.4 on 2021-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0007_mdlsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlsettings',
            name='ipAddress',
            field=models.TextField(default=''),
        ),
    ]
