# Generated by Django 3.1.4 on 2021-02-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0008_mdlsettings_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlsettings',
            name='bg_color',
            field=models.TextField(default='#000000'),
        ),
    ]
