# Generated by Django 3.1.4 on 2021-02-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0009_mdlsettings_bg_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdlsettings',
            old_name='bg_color',
            new_name='bgColor',
        ),
    ]
