# Generated by Django 3.1.4 on 2021-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_messages', '0013_auto_20210225_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlsettings',
            name='flashPeriod',
            field=models.FloatField(default=1.5),
        ),
    ]
